"""
ROS Helper Subagent for Claude Code
Parses ROS2 examples and generates appropriate code snippets
"""
from .base_subagent import BaseSubagent
from typing import Dict, Any, Optional
import re
import json


class RosHelper(BaseSubagent):
    """
    ROS Helper subagent that parses ROS2 examples and generates code snippets
    """
    
    def __init__(self):
        super().__init__(
            name="ros-helper",
            description="A specialist in ROS2 (Robot Operating System 2) that can parse ROS2 examples, generate launch files, nodes, and suggest appropriate ROS2 commands. Handles topics, services, actions, packages, and common ROS2 patterns."
        )
    
    async def execute(self, query: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute the ROS Helper subagent
        
        Args:
            query: User query about ROS2
            context: Additional context
            
        Returns:
            Dictionary containing parsed information and code suggestions
        """
        # Define a system prompt specific to ROS2
        system_prompt = """
You are a ROS2 (Robot Operating System 2) expert assistant. Your role is to help users understand ROS2 concepts, create ROS2 code, and provide ROS2-specific commands and configurations.

When responding:
1. Always provide valid ROS2 code in Python or C++
2. Include appropriate comments explaining ROS2 concepts
3. Follow ROS2 best practices for node structure, topics, services, and actions
4. Include package.xml and setup.py info when relevant
5. Suggest appropriate ROS2 commands for building, running, and debugging

Format your response as a JSON object with the following structure:
{
  "summary": "Brief summary of what you're providing",
  "code_snippets": [
    {
      "language": "python|cpp|bash|xml|yaml",
      "title": "Brief title",
      "code": "The actual code",
      "description": "What this code does"
    }
  ],
  "commands": ["ros2 run...", "ros2 launch...", etc.],
  "explanation": "Detailed explanation of the solution"
}
"""
        
        # Create the prompt for Claude
        prompt = f"""
The user has a question about ROS2 (Robot Operating System 2):

Query: {query}

Context: {context or 'No additional context provided'}

Please provide appropriate code snippets, ROS2 commands, explanations, and launch files as needed.
"""
        
        # Get response from Claude
        claude_response = self.get_claude_completion(prompt, system_prompt)
        
        # Try to parse the response as JSON
        try:
            # Attempt to extract JSON from Claude's response
            json_match = re.search(r'\{.*\}', claude_response, re.DOTALL)
            if json_match:
                result = json.loads(json_match.group())
            else:
                # If no JSON found, return a structured response
                result = {
                    "summary": f"ROS2 assistance for: {query}",
                    "code_snippets": [{
                        "language": "python",
                        "title": "Sample ROS2 Node",
                        "code": "# This would be a ROS2 node generated by Claude based on your query",
                        "description": "Sample ROS2 code based on your request"
                    }],
                    "commands": ["# ROS2 commands would be here"],
                    "explanation": claude_response
                }
        except json.JSONDecodeError:
            # If JSON parsing fails, create a structured response
            result = {
                "summary": f"ROS2 assistance for: {query}",
                "code_snippets": [{
                    "language": "text",
                    "title": "Response",
                    "code": claude_response,
                    "description": "Claude's response to your ROS2 query"
                }],
                "commands": [],
                "explanation": "Response generated from Claude's text"
            }
        
        return result